# Generated by Django 5.1.1 on 2024-09-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='balance',
        ),
        migrations.AddField(
            model_name='clients',
            name='purchase_history',
            field=models.CharField(default=None, max_length=500, verbose_name='История покупок'),
        ),
    ]
