# Generated by Django 5.1.1 on 2024-09-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_clients_balance_clients_purchase_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
    ]
