# Generated by Django 5.1.1 on 2024-09-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_clients_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clients',
        ),
    ]
