# Generated by Django 5.1.1 on 2024-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstapp', '0004_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(default=None, max_length=100, verbose_name='Фамилия')),
                ('purchase_history', models.CharField(default=None, max_length=500, verbose_name='История покупок')),
                ('dor', models.DateField(auto_now=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
