# Generated by Django 5.1.1 on 2024-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('count', models.IntegerField(verbose_name='Кол-во поступившее')),
                ('count_left', models.IntegerField(verbose_name='Кол-во оставшееся')),
                ('price_selling', models.FloatField(verbose_name='Цена продажи')),
                ('price_purchase', models.FloatField(verbose_name='Цена закупки')),
                ('doc', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
            ],
        ),
    ]
