# Generated by Django 5.1.1 on 2024-09-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date_of_last_purchase',
            field=models.DateTimeField(default=None, verbose_name='Дата и время последней покупки'),
        ),
    ]
