# Generated by Django 5.1.1 on 2024-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_clients_date_of_last_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tags',
            field=models.CharField(default='game_PC', max_length=100, verbose_name='Тэги'),
        ),
    ]
