# Generated by Django 5.1.1 on 2024-09-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tags',
        ),
    ]
