# Generated by Django 5.1.1 on 2024-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_delete_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Тэг')),
                ('tag_RU', models.CharField(max_length=100, verbose_name='Тэг на русском')),
            ],
        ),
    ]
