# Generated by Django 5.1.1 on 2024-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(default='Санкт-Петербург', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
    ]
