# Generated by Django 5.1.1 on 2024-09-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_clients_city_clients_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=None, verbose_name='Скидка %'),
            preserve_default=False,
        ),
    ]
