# Generated by Django 4.2.3 on 2024-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pic',
            field=models.ImageField(blank=True, upload_to='firstapp/img'),
        ),
    ]
