# Generated by Django 4.2.3 on 2024-10-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_alter_products_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
    ]
