# Generated by Django 4.2.3 on 2024-10-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_remove_products_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount2',
            field=models.IntegerField(blank=True, default=10, verbose_name='Скидка %'),
        ),
    ]
